title: PhillipKittelson.com
description: A blog from a security professional
show_downloads: false
timezone: America/New_York
google_analytics: G-1FEEX4ER1Z
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
