# Curated Training List
# Threat Hunter
- source: Cyborg Security
  title: Begin Your Hunt The Threat Hunting Workshop
  type: Workshop
  category: foundational
  summary: Threat hunting workshop
  logo: cyborg.png
  alt: Begin Your Hunt The Threat Hunting Workshop
  url: https://www.cyborgsecurity.com/our-webinars/webinars/begin-your-hunt-the-threat-hunting-workshop/
