# Threat Hunter
- category: Foundational
  training:
    - title: Threat Hunting Workshop
      provider: Cyborg Security
      url: https://www.cyborgsecurity.com/our-webinars/webinars/begin-your-hunt-the-threat-hunting-workshop/
    - title: Threat Hunting Level 1
      provider: Active Counter Measures
      url: https://www.activecountermeasures.com/hunt-training/
- category: Other
  training:
    - title: Threat Hunting with VirusTotal
      provider: VirusTotal
      url: https://www.youtube.com/watch?v=UZJ7j7t9cLc
- category: Labs
  training:
    - title: Persistence
      provider: Cyborg Security
      url: https://www.cyborgsecurity.com/our-webinars/webinars/upcoming-threat-hunting-workshop-persistence-is-futile/
    - title: Execution
      provider: Cyborg Security
      url: https://www.cyborgsecurity.com/our-webinars/webinars/threat-hunting-workshop-hunting-for-execution/
    - title: Defense Evasion
      provider: Cyborg Security
      url: https://www.cyborgsecurity.com/our-webinars/webinars/threat-hunting-workshop-4-hunting-for-defense-evasion/
    - title: Credential Access
      provider: Cyborg Security
      url: https://www.cyborgsecurity.com/our-webinars/webinars/threat-hunting-workshop-hunting-for-credential-access/
    - title: Lateral Movement
      provider: Cyborg Security
      url: https://www.cyborgsecurity.com/our-webinars/webinars/threat-hunting-workshop-hunting-for-lateral-movement/
    - title: Impact
      provider: Cyborg Security
      url: https://www.cyborgsecurity.com/our-webinars/webinars/threat-hunting-workshop-hunting-for-impact/
    - title: Exfiltration
      provider: Cyborg Security
      url: https://www.cyborgsecurity.com/threat-hunting-workshops/threat-hunting-workshop-8-hunting-for-exfiltration/
    - title: Privilege Escalation
      provider: Cyborg Security
      url: https://www.cyborgsecurity.com/threat-hunting-workshops/threat-hunting-workshop-hunting-for-privilege-escalation/
    - title: Initial Access
      provider: Cyborg Security
      url: https://www.cyborgsecurity.com/threat-hunting-workshops/threat-hunting-workshop-10-hunting-for-initial-access/
- categroy: Tools
  training:
    - title: CyberChef
      provider: GCHQ
      url: https://gchq.github.io/CyberChef/
    - title: IOC Fang
      url: https://ioc-fang.github.io/
    - title: VirusTotal
      url: https://www.virustotal.com/
    - title: URLScan.io
      url: https://urlscan.io/