# Training Paths
- role: Cyber Threat Hunter
  status: pending
  link: training-hunter.html
- role: Secuirty Operations Center (SOC) Analyst
  status: pending
- role: Phishing Analyst
  status: pending