# Training Paths
- role: Cyber Threat Hunter
  status: developing
  link: training-hunter.html
- role: Secuirty Operations Center (SOC) Analyst
  status: developing
  link: training-soc.html
- role: Phishing Analyst
  status: pending