# Curated Training List
# Threat Hunter
- source: Cyborg Security
  title: Begin Your Hunt The Threat Hunting Workshop
  type: Workshop
  category: workshop
  summary: Threat hunting workshop
  logo: cyborg.png
  alt: Begin Your Hunt The Threat Hunting Workshop
