#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --ignore-status-codes "999,401,404" --check-html --check-sri
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-architect.gemspec
